kind: pipeline
type: docker
name: default

trigger:
  event:
    - push

steps:
  - name: build
    image: node:20
    commands:
      - cd cryptide_project
      - npm install --legacy-peer-deps
      - CI=false npm run build

  - name: code-analysis
    image: node:20
    environment:
      SONAR_TOKEN:
        from_secret: SECRET_SONAR_LOGIN_CRYPTIDE
    commands:
      - export SONAR_SCANNER_VERSION=4.7.0.2747
      - export SONAR_SCANNER_HOME=$HOME/.sonar/sonar-scanner-$SONAR_SCANNER_VERSION-linux
      - curl --create-dirs -sSLo $HOME/.sonar/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-$SONAR_SCANNER_VERSION-linux.zip
      - unzip -o $HOME/.sonar/sonar-scanner.zip -d $HOME/.sonar/
      - export PATH=$SONAR_SCANNER_HOME/bin:$PATH
      - export SONAR_SCANNER_OPTS="-server"
      - sonar-scanner -D sonar.projectKey=Cryptid -D sonar.sources=. -D sonar.host.url=https://codefirst.iut.uca.fr/sonar
    secrets: [SECRET_SONAR_LOGIN_CRYPTIDE]
    settings:
      sonar_host: https://codefirst.iut.uca.fr/sonar/
      sonar_token:
        from_secret: SECRET_SONAR_LOGIN_CRYPTIDE